### ISSUE TITLE
Some Github connections keep giving a Bad Gateway response

### ISSUE THREAD

**Issue by dschreij** [CenterForOpenScience/waterbutler#179] opened 2017-01-04 14:37 UTC
See https://github.com/dschreij/QOpenScienceFramework/issues/5 for a specific occurrence of this issue. In our OSF extension for OpenSesame, we make sure that users get notified of any error that occurs with requests to OSF/Waterbutler. A very prominent and annoying error message that pops up every time for some linked Github repositorie is:

~~~
server replied: Bad Gateway
~~~

is this something we can fix, or is it inherent to how Waterbutler currently communicates with Github?

**Comment by felliott** [comment] 2017-01-04 14:44
Hey @dschreij!

That sounds like the same issue that @emetsger reported here: https://github.com/CenterForOpenScience/osf.io/issues/6062.  I don't know what's causing it, but I'll have another look.  Have you noticed that this happens with a particular action?  I ran into a similar issue in May of last year where trying to download one particular file caused intermittent 502s.  I reported it to GH and they fixed it at the end of June.  If I can associate it with a particular type of request, I'll submit another bug report to them.

Cheers,
Fitz

**Comment by dschreij** [comment] 2017-01-04 16:07
Hi Fitz,
I don't really know the specific cause, as we build an entire tree of OSF projects and their contents at application startup. Mainly this involves sending GET requests to OSF to provide lists of project and folder contents.

Maybe @smathot has a better idea of this?

**Comment by smathot** [comment] 2017-01-04 19:47
What exactly happens behind the scenes is beyond me. But it's clear what happens and when.

- In OpenSesame, I log into the OSF.
- Then when I open the OSF explorer widget (but not before), I always receive the following error message:

![image](https://cloud.githubusercontent.com/assets/594936/21656427/6e525ffc-d2be-11e6-9264-ad3f27caca92.png)

The error message appears to be harmless. It occurs on all operating systems that I've tried.

The error is clearly due to one of my projects being linked to a GitHub repository. However, that's the case for a few projects, and because they all have similar folder structures, I cannot tell from the error message which repository is the culprit.

Is this helpful at all?

**Comment by felliott** [comment] 2017-01-04 19:50
Hey @smathot!

It's very helpful!  When did you take that screenshot?  That's the OSF API reporting Bad Gateway, so it's possible there's a different error happening on the WB side.  I'll look through our logs and see if I can correlate them.

Cheers,
Fitz

**Comment by smathot** [comment] 2017-01-04 19:54
I took the screenshot just now. But the exact same error has been occurring systematically for months.

**Comment by felliott** [comment] 2017-01-04 20:00
Gotcha.  I think I found the error in the logs, it was hiding under an unremarkable name.  That should hopefully give me enough to pinpoint it.  Do you mind pointing me to the linked repo on GH (if it's public)?  This might be tied into a fix we put in awhile ago to avoid a different type of error.  I'd like to see if that repo might be triggering this fix.

Cheers,
Fitz

**Comment by felliott** [comment] 2017-01-04 21:16
I know what's causing this.  The problem is that the modified timestamp for file `/foo/bar` is returned if you query `/foo/bar` directly, but is missing if you query `/foo/`.  IIRC, this was a conscious decision because the GH tree endpoint returns less information than the blob endpoint, but the blob endpoint has some unreliabilites.  I'll try to fix it in WB, but if I can't, the OSF will need to be taught to handle missing modified timestamps better.

**Comment by felliott** [comment] 2017-01-04 21:56
After some digging, I remember the problem.  When fetching metadata for a file, we first get the latest commit to affect that file.  The files `modified` property is the commit date.  When fetching metadata for a folder, we'd have to do an extra API call for each file in the directory to get the latest commit.  We already bump up against GH's rate limits, so this is impractical for us.  Since I can't fix this in WB, I'll have to fix OSF to handle missing `modified`s more gracefully.  I'm closing this bug, but I'll continue working on it over on https://github.com/CenterForOpenScience/osf.io/issues/6062.

Cheers,
@felliott

**Closed by felliott** 2017-01-04 21:56 UTC

**Comment by smathot** [comment] 2017-01-05 08:12
Excellent, thank you!

**Comment by dschreij** [comment] 2017-01-05 12:01
Thanks Fitz!
